"""Build frontend/static/js/globe-land.js: dots on land for the landing-page globe.

Run once:  python scripts/build_globe_land.py [path/to/land-110m.json]

Downloads Natural Earth land at 1:110m (world-atlas@2, TopoJSON) from jsdelivr,
samples an even lat/lon grid and keeps the points that fall on land. The output
is a flat [lon, lat, lon, lat, ...] array read by frontend/static/js/globe.js.
Antarctica is left out (the globe is tilted so it would barely show, and its
ring wraps the pole, which plain point-in-polygon does not handle).
"""
import json
import math
import ssl
import sys
import urllib.request
from pathlib import Path

SOURCE = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json"
OUT = Path(__file__).resolve().parent.parent / "frontend" / "static" / "js" / "globe-land.js"
STEP = 2.2          # degrees between dots along a meridian
MIN_LAT = -58.0     # skip Antarctica


def decode_arcs(topo):
    scale, translate = topo["transform"]["scale"], topo["transform"]["translate"]
    arcs = []
    for arc in topo["arcs"]:
        x = y = 0
        points = []
        for dx, dy in arc:
            x += dx
            y += dy
            points.append((x * scale[0] + translate[0], y * scale[1] + translate[1]))
        arcs.append(points)
    return arcs


def ring_points(ring, arcs):
    points = []
    for index in ring:
        arc = arcs[index] if index >= 0 else list(reversed(arcs[~index]))
        points.extend(arc[1:] if points else arc)
    return points


def unwrap(ring):
    """Make longitudes continuous across the ±180° line (eastern Russia, Fiji),
    so a ring that crosses it isn't read as a band round the whole globe."""
    out = [ring[0]]
    for x, y in ring[1:]:
        prev = out[-1][0]
        while x - prev > 180:
            x -= 360
        while x - prev < -180:
            x += 360
        out.append((x, y))
    return out


def polygons(topo):
    arcs = decode_arcs(topo)
    for geometry in topo["objects"]["land"]["geometries"]:
        parts = geometry["arcs"] if geometry["type"] == "MultiPolygon" else [geometry["arcs"]]
        for part in parts:
            rings = [unwrap(ring_points(ring, arcs)) for ring in part]
            xs = [p[0] for p in rings[0]]
            ys = [p[1] for p in rings[0]]
            yield rings, (min(xs), min(ys), max(xs), max(ys))


def inside(ring, x, y):
    hit = False
    j = len(ring) - 1
    for i in range(len(ring)):
        xi, yi = ring[i]
        xj, yj = ring[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
            hit = not hit
        j = i
    return hit


def on_land(polys, x, y):
    for rings, (x0, y0, x1, y1) in polys:
        for xs in (x, x - 360, x + 360):  # unwrapped rings may sit past ±180
            if x0 <= xs <= x1 and y0 <= y <= y1 and inside(rings[0], xs, y):
                if not any(inside(hole, xs, y) for hole in rings[1:]):
                    return True
    return False


def main():
    if len(sys.argv) > 1:
        topo = json.loads(Path(sys.argv[1]).read_text())
    else:
        try:  # python.org builds on macOS ship without CA certificates
            import certifi
            context = ssl.create_default_context(cafile=certifi.where())
        except ImportError:
            context = None
        with urllib.request.urlopen(SOURCE, timeout=30, context=context) as response:
            topo = json.load(response)
    polys = [p for p in polygons(topo) if p[1][3] > MIN_LAT]

    flat = []
    lat = -90 + STEP / 2
    while lat < 90:
        if lat >= MIN_LAT:
            # Fewer dots towards the poles so spacing stays even on the sphere.
            count = max(1, round(360 / STEP * math.cos(math.radians(lat))))
            for k in range(count):
                lon = -180 + (k + 0.5) * 360 / count
                if on_land(polys, lon, lat):
                    flat += [round(lon, 1), round(lat, 1)]
        lat += STEP

    body = json.dumps(flat, separators=(",", ":"))
    OUT.write_text(
        "/* Generated by scripts/build_globe_land.py from Natural Earth 1:110m land "
        "(world-atlas@2). Flat [lon, lat, ...]. Do not edit by hand. */\n"
        f"window.GLOBE_LAND={body};\n"
    )
    print(f"{len(flat) // 2} land dots, {OUT.stat().st_size / 1024:.1f} KB -> {OUT}")


if __name__ == "__main__":
    main()
